/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package razor.model.taskNotes;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author scast
 */
public class TaskNotesView extends javax.swing.JPanel {
    
    private TaskNotesModel tareas;
    private String str;
    private Color oscuro = new Color (55,64,81);
    private Color marron = new Color (158,132,76);
    private Color masoscuro = new Color (43,50,62);
    
    public TaskNotesView() {
        
        tareas = new TaskNotesModel ();
        tareas.leerFichero();
        str = tareas.toStringTareasPendientes();

        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEliminarTarea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelCompletarTarea = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelAgregarTarea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelTareasCompletadas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelTareasPendientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTareas = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 64, 81));
        setPreferredSize(new java.awt.Dimension(874, 600));

        jPanel1.setBackground(new java.awt.Color(55, 64, 81));

        panelEliminarTarea.setBackground(new java.awt.Color(43, 50, 62));
        panelEliminarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEliminarTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEliminarTareaMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar Tarea");

        javax.swing.GroupLayout panelEliminarTareaLayout = new javax.swing.GroupLayout(panelEliminarTarea);
        panelEliminarTarea.setLayout(panelEliminarTareaLayout);
        panelEliminarTareaLayout.setHorizontalGroup(
            panelEliminarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarTareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelEliminarTareaLayout.setVerticalGroup(
            panelEliminarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCompletarTarea.setBackground(new java.awt.Color(43, 50, 62));
        panelCompletarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCompletarTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCompletarTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCompletarTareaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Completar Tarea");

        javax.swing.GroupLayout panelCompletarTareaLayout = new javax.swing.GroupLayout(panelCompletarTarea);
        panelCompletarTarea.setLayout(panelCompletarTareaLayout);
        panelCompletarTareaLayout.setHorizontalGroup(
            panelCompletarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompletarTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCompletarTareaLayout.setVerticalGroup(
            panelCompletarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompletarTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAgregarTarea.setBackground(new java.awt.Color(43, 50, 62));
        panelAgregarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAgregarTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAgregarTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAgregarTareaMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Tarea");

        javax.swing.GroupLayout panelAgregarTareaLayout = new javax.swing.GroupLayout(panelAgregarTarea);
        panelAgregarTarea.setLayout(panelAgregarTareaLayout);
        panelAgregarTareaLayout.setHorizontalGroup(
            panelAgregarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAgregarTareaLayout.setVerticalGroup(
            panelAgregarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarTareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        PanelTareasCompletadas.setBackground(new java.awt.Color(43, 50, 62));
        PanelTareasCompletadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTareasCompletadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelTareasCompletadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelTareasCompletadasMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tareas Completadas");

        javax.swing.GroupLayout PanelTareasCompletadasLayout = new javax.swing.GroupLayout(PanelTareasCompletadas);
        PanelTareasCompletadas.setLayout(PanelTareasCompletadasLayout);
        PanelTareasCompletadasLayout.setHorizontalGroup(
            PanelTareasCompletadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTareasCompletadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTareasCompletadasLayout.setVerticalGroup(
            PanelTareasCompletadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTareasCompletadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTareasPendientes.setBackground(new java.awt.Color(43, 50, 62));
        panelTareasPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTareasPendientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTareasPendientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTareasPendientesMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tareas Pendientes");

        javax.swing.GroupLayout panelTareasPendientesLayout = new javax.swing.GroupLayout(panelTareasPendientes);
        panelTareasPendientes.setLayout(panelTareasPendientesLayout);
        panelTareasPendientesLayout.setHorizontalGroup(
            panelTareasPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTareasPendientesLayout.setVerticalGroup(
            panelTareasPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTareasPendientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panelCompletarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panelEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(PanelTareasCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(panelTareasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTareasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTareasCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCompletarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        textTareas.setEditable(false);
        textTareas.setBackground(new java.awt.Color(43, 50, 62));
        textTareas.setColumns(20);
        textTareas.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        textTareas.setForeground(new java.awt.Color(255, 255, 255));
        textTareas.setRows(5);
        textTareas.setText(tareas.toStringTareasPendientes());
        textTareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textTareas.setCaretColor(new java.awt.Color(55, 64, 81));
        jScrollPane1.setViewportView(textTareas);

        jPanel2.setBackground(new java.awt.Color(43, 50, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tareas");

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha dd/mm/aa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Listeners">
    private void panelAgregarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarTareaMouseClicked
        // TODO add your handling code here:
        String tarea = JOptionPane.showInputDialog(null,"Introduce la tarea: ");
        tareas.agregarTarea(tareas.getFileName1(),tarea);
        textTareas.setText(tareas.toStringTareasPendientes());
    }//GEN-LAST:event_panelAgregarTareaMouseClicked
    
    private void panelCompletarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompletarTareaMouseClicked
        // TODO add your handling code here:
        int num = Integer.parseInt(JOptionPane.showInputDialog(null,"Introduce el numero de la tarea: " ));
        tareas.completarTarea(num);
        textTareas.setText(tareas.toStringTareasPendientes());
    }//GEN-LAST:event_panelCompletarTareaMouseClicked

    private void panelEliminarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarTareaMouseClicked
        // TODO add your handling code here:
        int num = Integer.parseInt(JOptionPane.showInputDialog(null,"Introduce el numero de la tarea: " ));
        tareas.eliminarTarea(num);
        textTareas.setText(tareas.toStringTareasPendientes());
    }//GEN-LAST:event_panelEliminarTareaMouseClicked

    private void panelEliminarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarTareaMouseExited
        // TODO add your handling code here:
        panelEliminarTarea.setBackground(masoscuro);
    }//GEN-LAST:event_panelEliminarTareaMouseExited

    private void panelTareasPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTareasPendientesMouseClicked
        // TODO add your handling code here:
        textTareas.setText(tareas.toStringTareasPendientes());
        panelTareasPendientes.setBackground(marron);
        if (PanelTareasCompletadas.getBackground() == marron)
            PanelTareasCompletadas.setBackground(masoscuro);
    }//GEN-LAST:event_panelTareasPendientesMouseClicked

    private void PanelTareasCompletadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTareasCompletadasMouseClicked
        // TODO add your handling code here:
        textTareas.setText(tareas.toStringTareasCompletadas());
        PanelTareasCompletadas.setBackground(marron);
        if (panelTareasPendientes.getBackground() == marron)
            panelTareasPendientes.setBackground(masoscuro);
    }//GEN-LAST:event_PanelTareasCompletadasMouseClicked

    private void panelEliminarTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarTareaMouseEntered
        // TODO add your handling code here:
        panelEliminarTarea.setBackground(marron);
    }//GEN-LAST:event_panelEliminarTareaMouseEntered

    private void panelAgregarTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarTareaMouseEntered
        // TODO add your handling code here:
        panelAgregarTarea.setBackground(marron);
    }//GEN-LAST:event_panelAgregarTareaMouseEntered

    private void panelAgregarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarTareaMouseExited
        // TODO add your handling code here:
        panelAgregarTarea.setBackground(masoscuro);
    }//GEN-LAST:event_panelAgregarTareaMouseExited

    private void panelCompletarTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompletarTareaMouseEntered
        // TODO add your handling code here:
        panelCompletarTarea.setBackground(marron);
    }//GEN-LAST:event_panelCompletarTareaMouseEntered

    private void panelCompletarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompletarTareaMouseExited
        // TODO add your handling code here:
        panelCompletarTarea.setBackground(masoscuro);
    }//GEN-LAST:event_panelCompletarTareaMouseExited
    
    private void PanelTareasCompletadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTareasCompletadasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTareasCompletadasMouseEntered

    private void PanelTareasCompletadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTareasCompletadasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTareasCompletadasMouseExited

    private void panelTareasPendientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTareasPendientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTareasPendientesMouseEntered

    private void panelTareasPendientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTareasPendientesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTareasPendientesMouseExited
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTareasCompletadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAgregarTarea;
    private javax.swing.JPanel panelCompletarTarea;
    private javax.swing.JPanel panelEliminarTarea;
    private javax.swing.JPanel panelTareasPendientes;
    public javax.swing.JTextArea textTareas;
    // End of variables declaration//GEN-END:variables
}
